
-- Tabela de usuários
create table users (
  id bigint generated by default as identity primary key,
  email varchar(100) unique not null,
  username varchar(100) not null,
  password varchar(255) not null,
  is_admin boolean default false
);

-- Tabela de conteúdo
create table conteudo (
  id bigint generated by default as identity primary key,
  capa text not null,
  nome varchar(255) not null,
  data_lancamento varchar(20),
  duracao varchar(20),
  tipo text check (tipo in ('filme', 'serie')) not null
);

-- Inserir usuário admin (senha: Syntax@123)
insert into users (email, username, password, is_admin)
values (
  'syntaxsouls@admin.duo',
  'Admin',
  '$2b$10$K3OMaX4FTv1MVl0qSq5cNeiJ08jRbjWv2BjZ2IHOw8ynv4f6A.q1O',
  true
)
-- Tabela de usuários
create table users (
  id bigint generated by default as identity primary key,
  email varchar(100) unique not null,
  username varchar(100) not null,
  password varchar(255) not null,
  is_admin boolean default false
);

-- Tabela de conteúdo
create table conteudo (
  id bigint generated by default as identity primary key,
  capa text not null,
  nome varchar(255) not null,
  data_lancamento varchar(20),
  duracao varchar(20),
  tipo text check (tipo in ('filme', 'serie')) not null
);

-- Inserir usuário admin (senha: Syntax@123)
insert into users (email, username, password, is_admin)
values (
  'syntaxsouls@admin.duo',
  'Admin',
  '$2b$10$K3OMaX4FTv1MVl0qSq5cNeiJ08jRbjWv2BjZ2IHOw8ynv4f6A.q1O',
  true
); 